# Generated by Django 6.0.1 on 2026-02-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_hostelasset_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelasset',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
