# Generated by Django 6.0.1 on 2026-02-04 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_hosteldiscipline_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelasset',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hostel.room'),
        ),
    ]
