# Generated by Django 6.0.1 on 2026-02-04 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_alter_hostelasset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelasset',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='hostel.hostel'),
        ),
    ]
