# Generated by Django 6.0.1 on 2026-02-24 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_hostelasset_hostel'),
        ('students', '0007_alter_student_is_active_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelattendance',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='hostelattendance',
            index=models.Index(fields=['student', 'date'], name='hostel_host_student_ac9c53_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelattendance',
            index=models.Index(fields=['date', 'session'], name='hostel_host_date_d61d4f_idx'),
        ),
    ]
