# Generated by Django 6.0.1 on 2026-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_alter_hostelattendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelattendance',
            name='session',
            field=models.CharField(choices=[('MORNING', 'Morning Call'), ('EVENING', 'Evening Call'), ('NIGHT', 'Night Call'), ('SPECIAL', 'Special Check')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hostelattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('PERMITTED', 'On Leave/Exeat'), ('PERMISSION', 'On Permission'), ('SICK', 'Sick Bay/Hospital')], max_length=15),
        ),
    ]
