# Generated by Django 6.0.1 on 2026-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PRINCIPAL', 'Principal'), ('DEPUTY', 'Deputy Principal'), ('DOS', 'Director of Studies'), ('REGISTRAR', 'Admissions Registrar'), ('TEACHER', 'Teacher'), ('WARDEN', 'Hostel Warden'), ('NURSE', 'Nurse'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], default='STUDENT', max_length=20),
        ),
    ]
