# Generated by Django 6.0.1 on 2026-03-14 19:05

from django.db import migrations, models

def fix_emails(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if not user.email:
            placeholder = f"{user.username}@placeholder.com"
            if User.objects.filter(email=placeholder).exists():
                placeholder = f"{user.username}.{user.id}@placeholder.com"
            user.email = placeholder
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(fix_emails),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
