# Generated by Django 6.0.1 on 2026-02-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicyear_gradesystem_subjectgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_percentage', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('class_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('subject', 'class_grade')},
            },
        ),
    ]
