# Generated by Django 6.0.1 on 2026-02-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.IntegerField(default=1, help_text='Numeric level for promotion logic (e.g. 1 for Form 1, 4 for Form 4)'),
        ),
        migrations.AddField(
            model_name='term',
            name='is_final_term',
            field=models.BooleanField(default=False, help_text='If true, reaching the end_date will trigger end-of-year processes (promotion).'),
        ),
    ]
