# Generated by Django 6.0.1 on 2026-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Designates the primary contact for financial and medical alerts.'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
