# Generated by Django 6.0.1 on 2026-02-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_parent_is_primary_alter_parent_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
