# Generated by Django 6.0.1 on 2026-02-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_parent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('ALUMNI', 'Alumni'), ('TRANSFERRED', 'Transferred Out')], db_index=True, default='ACTIVE', max_length=15),
        ),
    ]
