# Generated by Django 6.0.1 on 2026-02-20 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classsubject_studentsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='grade_system',
            field=models.ForeignKey(blank=True, help_text='Specific grading system for this exam', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.gradesystem'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.term'),
        ),
    ]
