# Generated by Django 6.0.1 on 2026-02-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_protect_exam_term_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
