# Generated by Django 6.0.1 on 2026-03-15 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_class_level_term_is_final_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date_started',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
