# Generated by Django 6.0.1 on 2026-02-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_guardian_email_student_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='residence_details',
            field=models.CharField(blank=True, help_text='Auto-synced from Hostel Allocation', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_details',
            field=models.CharField(blank=True, help_text='Auto-synced from Transport Allocation', max_length=100),
        ),
    ]
