# Generated by Django 6.0.1 on 2026-03-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_is_active_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_balance',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
