# Generated by Django 6.0.1 on 2026-02-05 10:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_syllabuscoverage'),
        ('finance', '0002_budget_expensecategory_feeitem_financialtransaction_and_more'),
        ('students', '0003_student_residence_details_student_transport_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('CREDIT', 'Credit Note (Reduce Debt)'), ('DEBIT', 'Debit Note (Increase Debt)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Staff Salary'), ('UTILITIES', 'Utilities (Water/Power)'), ('MAINTENANCE', 'Repairs & Maintenance'), ('SUPPLIES', 'Office/Class Supplies'), ('FOOD', 'Food & Provisions'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='feestructureitem',
            name='fee_item',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='items',
        ),
        migrations.RemoveField(
            model_name='feestructureitem',
            name='fee_structure',
        ),
        migrations.DeleteModel(
            name='FinancialTransaction',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.RemoveField(
            model_name='payrollprofile',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='studentfeerecord',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_generated']},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='recorded_by',
            new_name='approved_by',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='date_occurred',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='recorded_by',
            new_name='received_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='year',
        ),

        migrations.RemoveField(
            model_name='payment',
            name='date_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_reference',
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_to',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_scan',
            field=models.FileField(blank=True, null=True, upload_to='expenses/'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.class'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_generated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_finalized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERPAID', 'Overpaid')], default='UNPAID', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='term',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_received',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MPESA', 'M-Pesa'), ('CHEQUE', 'Cheque')], default='CASH', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adjustment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='fee_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.feestructure'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice'),
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='FeeItem',
        ),
        migrations.DeleteModel(
            name='FeeStructureItem',
        ),
        migrations.DeleteModel(
            name='PayrollProfile',
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
        migrations.DeleteModel(
            name='StudentFeeRecord',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_paid',
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('student', 'academic_year', 'term')},
        ),
    ]

