# Generated by Django 6.0.1 on 2026-02-18 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_payment_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERPAID', 'Overpaid')], db_index=True, default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_received',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
