# Generated by Django 6.0.1 on 2026-02-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_invoice_status_alter_payment_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='origin_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='origin_model',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='origin_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='origin_model',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
