# Generated by Django 6.0.1 on 2026-02-23 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_invoice_balance_alter_invoice_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_generated',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='term',
            field=models.IntegerField(db_index=True),
        ),
    ]
