# Generated by Django 6.0.1 on 2026-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_adjustment_created_at_invoiceitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
