# Generated by Django 6.0.1 on 2026-02-01 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0002_remove_student_guardian_email_student_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('route_code', models.CharField(max_length=10, unique=True)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='One way distance', max_digits=5)),
                ('timing_morning', models.TimeField(blank=True, null=True)),
                ('timing_evening', models.TimeField(blank=True, null=True)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_document', models.TextField(blank=True)),
                ('transport_fee_notes', models.TextField(blank=True)),
                ('max_wait_time_minutes', models.IntegerField(default=5)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Number Plate')),
                ('vehicle_type', models.CharField(choices=[('BUS', 'Bus'), ('VAN', 'Van'), ('MINIBUS', 'Minibus'), ('OTHER', 'Other')], default='BUS', max_length=10)),
                ('make_model', models.CharField(blank=True, max_length=100)),
                ('seating_capacity', models.IntegerField()),
                ('current_condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Needs Repair')], default='EXCELLENT', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'In Maintenance'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=15)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('inspection_expiry', models.DateField(blank=True, null=True)),
                ('logbook_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('license_type', models.CharField(default='Commercial', max_length=20)),
                ('years_experience', models.IntegerField(default=0)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='staff.staff')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=100)),
                ('pickup_time', models.TimeField()),
                ('dropoff_time', models.TimeField()),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='transport.route')),
            ],
        ),
        migrations.CreateModel(
            name='TransportAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=10)),
                ('pickup_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.pickuppoint')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='transport.route')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_allocation', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendant', models.CharField(blank=True, max_length=100)),
                ('trip_type', models.CharField(choices=[('MORNING', 'Morning Pickup'), ('EVENING', 'Evening Drop-off'), ('SPECIAL', 'Special Trip')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('odometer_start', models.IntegerField(blank=True, null=True)),
                ('odometer_end', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.driverprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TransportAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='transport.triplog')),
            ],
        ),
        migrations.CreateModel(
            name='TransportIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('LOW', 'Minor'), ('MEDIUM', 'Moderate'), ('HIGH', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.IntegerField()),
                ('receipt_no', models.CharField(blank=True, max_length=50)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage_at_service', models.IntegerField()),
                ('next_service_due', models.DateField()),
                ('performed_by', models.CharField(max_length=200)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='transport.vehicle')),
            ],
        ),
    ]
