# Generated by Django 6.0.1 on 2026-02-04 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportincident',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transportincident',
            name='severity',
            field=models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='mileage_at_service',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='next_service_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='performed_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
