# Generated by Django 6.0.1 on 2026-02-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_transportincident_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportincident',
            name='incident_type',
            field=models.CharField(default='ACCIDENT', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
