# Generated by Django 6.0.1 on 2026-02-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_transportincident_incident_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='distance_from_school',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance in KM', max_digits=5),
        ),
    ]
