# Generated by Django 6.0.1 on 2026-02-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_pickuppoint_distance_from_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='additional_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='distance_from_school',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance in KM', max_digits=8),
        ),
    ]
