# Generated by Django 6.0.1 on 2026-02-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_pickuppoint_additional_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='additional_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='distance_from_school',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance in KM', max_digits=10),
        ),
    ]
