# Generated by Django 6.0.1 on 2026-02-24 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_pickuppoint_additional_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triplog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='triplog',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='triplog',
            index=models.Index(fields=['date', 'vehicle'], name='transport_t_date_48d72c_idx'),
        ),
        migrations.AddIndex(
            model_name='triplog',
            index=models.Index(fields=['date', 'route'], name='transport_t_date_be0fa9_idx'),
        ),
    ]
