# Generated by Django 6.0.5 on 2026-05-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_alter_triplog_options_alter_triplog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
    ]
