# Generated by Django 6.0.1 on 2026-02-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
