# Generated by Django 6.0.1 on 2026-02-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_supabase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PRINCIPAL', 'Principal'), ('DEPUTY', 'Deputy Principal'), ('DOS', 'Director of Studies'), ('REGISTRAR', 'Admissions Registrar'), ('TEACHER', 'Teacher'), ('WARDEN', 'Hostel Warden'), ('NURSE', 'Nurse'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('DRIVER', 'Driver')], default='STUDENT', max_length=20),
        ),
    ]
