# Generated by Django 6.0.1 on 2026-03-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
