# Generated by Django 6.0.1 on 2026-02-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_residence_details_student_transport_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='students', to='students.parent'),
        ),
    ]
