# Generated by Django 6.0.1 on 2026-03-14 14:34

import django.db.models.deletion
from django.db import migrations, models


def migrate_departments(apps, schema_editor):
    Staff = apps.get_model('staff', 'Staff')
    Department = apps.get_model('staff', 'Department')
    for s in Staff.objects.all():
        dept_name = s.department_temp.strip() if s.department_temp else 'General'
        dept, _ = Department.objects.get_or_create(name=dept_name)
        s.department = dept
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='department',
            new_name='department_temp',
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='staff.department'),
        ),
        migrations.RunPython(
            code=migrate_departments,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department_temp',
        ),
    ]
