# Generated by Django 6.0.1 on 2026-03-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_department_alter_staff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, help_text='Work email — must be unique across all staff.', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone — must be unique across all staff.', max_length=20, null=True, unique=True),
        ),
    ]
