# Generated by Django 6.0.1 on 2026-04-29 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        ('staff', '0003_staff_unique_email_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='date',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='date_visited',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='pulse_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('REFERRED', 'Referred'), ('PENDING', 'Pending Follow-up')], default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
    ]
