# Generated by Django 6.0.1 on 2026-02-04 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_hostelasset_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldiscipline',
            name='severity',
            field=models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='MINOR', max_length=20),
        ),
        migrations.AddField(
            model_name='hostelmaintenance',
            name='date_reported',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
